apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
  labels:
    app: resterter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restarter
  namespace: default
  labels:
    app: resterter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restarter
  namespace: default
  labels:
    app: resterter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restarter
subjects:
- kind: ServiceAccount
  name: restarter
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iotagent-ul-resterter
  labels:
    cronjob: iotagent-ul-restarter
spec:
  concurrencyPolicy: Replace
  schedule: "0 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restarter
          containers:
          - name: iotagent-ul-restarter
            image: ${REPOSITORY}/tech-sketch/iotagent-ul-restarter:0.1.0
            imagePullPolicy: Always
            env:
            - name: NAMESPACE
              value: default
            - name: DEPLOYMENT_NAME
              value: iotagent-ul
          restartPolicy: OnFailure
