# -*- coding: utf-8 -*-

# environment variable name
ROBOT_SERVICE = 'ROBOT_SERVICE'
ROBOT_SERVICEPATH = 'ROBOT_SERVICEPATH'
ROBOT_TYPE = 'ROBOT_TYPE'
DEST_LED_SERVICE = 'DEST_LED_SERVICE'
DEST_LED_SERVICEPATH = 'DEST_LED_SERVICEPATH'
DEST_LED_TYPE = 'DEST_LED_TYPE'
ROBOT_STATE_CHECK_WAIT_SEC = 'ROBOT_STATE_CHECK_WAIT_SEC'

# current app
DEFAULT_ROBOT_STATE_CHECK_WAIT_SEC = 'DEFAULT_ROBOT_STATE_CHECK_WAIT_SEC'

# destination specification
DEST_LED_ID = 'dest_led_id'
DEST_FLOOR = 'floor'
DEST_POS_X = 'dest_pos_x'
DEST_POS_Y = 'dest_pos_y'

# robot state
WAITING = 'Waiting'
GUIDING = 'Guiding'
SUSPENDING = 'Suspending'
RETURNING = 'Returning'

# tablet
TABLET_SUFFIX = '_tablet'
