# -*- coding: utf-8 -*-

# environment variable name
ROBOT_SERVICE = 'ROBOT_SERVICE'
ROBOT_SERVICEPATH = 'ROBOT_SERVICEPATH'
ROBOT_TYPE = 'ROBOT_TYPE'
ROBOT_ID = 'ROBOT_ID'
TURTLEBOT_1_ID = 'TURTLEBOT_1_ID'
