# -*- coding: utf-8 -*-

# environment variable name
ROBOT_SERVICE = 'ROBOT_SERVICE'
ROBOT_SERVICEPATH = 'ROBOT_SERVICEPATH'
ROBOT_TYPE = 'ROBOT_TYPE'
ROBOT_FLOOR_MAP = 'ROBOT_FLOOR_MAP'
DEST_LED_SERVICE = 'DEST_LED_SERVICE'
DEST_LED_SERVICEPATH = 'DEST_LED_SERVICEPATH'
DEST_LED_TYPE = 'DEST_LED_TYPE'

# destination specification
DEST_LED_ID = 'dest_led_id'
DEST_FLOOR = 'floor'
DEST_POS = 'dest_pos'
