FROM python:3.6.5-alpine
MAINTAINER Nobuyuki Matsui <nobuyuki.matsui@gmail.com>

ARG LISTEN_PORT
ENV LISTEN_PORT ${LISTEN_PORT:-3000}

ARG SERVICE_PATH

ENV LOGGING_JSON /opt/logging.json

COPY ${SERVICE_PATH} /opt/app
COPY ./controller/controllerlibs/dist/ /opt/wheel

WORKDIR /opt/app

RUN apk update && \
    apk add --no-cache nginx supervisor && \
    apk add --no-cache --virtual .build python3-dev build-base linux-headers pcre-dev && \
    apk add --no-cache --virtual .pillow jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev \
                                         tiff-dev tk-dev tcl-dev harfbuzz-dev fribidi-dev && \
    pip install -r requirements/common.txt && \
    pip install -r requirements/production.txt && \
    pip install --no-index --find-links=/opt/wheel -r requirements/wheel.txt && \
    rm /etc/nginx/nginx.conf && \
    apk del --purge .build && \
    rm -r /root/.cache

COPY ./controller/docker/nginx.conf /etc/nginx/nginx.conf
COPY ./controller/docker/flask-nginx.conf /etc/nginx/conf.d/flask-nginx.conf
COPY ./controller/docker/uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY ./controller/docker/supervisord.conf /etc/supervisord.conf
COPY ./controller/docker/entrypoint.sh /opt/entrypoint.sh
COPY ./controller/docker/logging.json /opt/logging.json

RUN chmod a+x /opt/entrypoint.sh

ENTRYPOINT /opt/entrypoint.sh
