# -*- coding: utf-8 -*-

# flask config
CAMERA_HEATMAP_TEMPLATE = 'CAMERA_HEATMAP_TEMPLATE'

# environment variable name
BEARER_AUTH = 'BEARER_AUTH'
PREFIX = 'PREFIX'
MONGODB_ENDPOINT = 'MONGODB_ENDPOINT'
MONGODB_REPLICASET = 'MONGODB_REPLICASET'
MONGODB_DATABASE = 'MONGODB_DATABASE'
MONGODB_COLLECTION = 'MONGODB_COLLECTION'

# camera
CAMERA_ROW = 9
CAMERA_COLUMN = 12
CAMERA_1F_1 = "1f-1"
CAMERA_1F_2 = "1f-2"
CAMERA_2F_1 = "2f-1"
