# -*- coding: utf-8 -*-

# flask config
CAMERA_HEATMAP_TEMPLATE = 'CAMERA_HEATMAP_TEMPLATE'

# environment variable name
BEARER_AUTH = 'BEARER_AUTH'
PREFIX = 'PREFIX'
MONGODB_ENDPOINT = 'MONGODB_ENDPOINT'
MONGODB_REPLICASET = 'MONGODB_REPLICASET'
MONGODB_DATABASE = 'MONGODB_DATABASE'
MONGODB_COLLECTION = 'MONGODB_COLLECTION'
