# -*- coding: utf-8 -*-

# environment variable name
INTERVAL_SEC = 'INTERVAL_SEC'
SUSPENDING_SEC_MAX = 'SUSPENDING_SEC_MAX'
ROBOT_SERVICE = 'ROBOT_SERVICE'
ROBOT_SERVICEPATH = 'ROBOT_SERVICEPATH'
ROBOT_TYPE = 'ROBOT_TYPE'
DEST_LED_SERVICE = 'DEST_LED_SERVICE'
DEST_LED_SERVICEPATH = 'DEST_LED_SERVICEPATH'
DEST_LED_TYPE = 'DEST_LED_TYPE'

# default value
DEFAULT_INTERVAL_SEC = 1
DEFAULT_SUSPENDING_SEC_MAX = 15
TARGET_FLOOR = (1, 2, )

# destination specification
DEST_LED_ID = 'dest_led_id'
DEST_FLOOR = 'floor'
DEST_POS_X = 'dest_pos_x'
DEST_POS_Y = 'dest_pos_y'

# robot state
WAITING = 'Waiting'
GUIDING = 'Guiding'
SUSPENDING = 'Suspending'
RETURNING = 'Returning'
