# -*- coding: utf-8 -*-

# environment variable name
PEPPER_SERVICE = 'PEPPER_SERVICE'
PEPPER_SERVICEPATH = 'PEPPER_SERVICEPATH'
PEPPER_TYPE = 'PEPPER_TYPE'
PEPPER_IDPATTERN = 'PEPPER_IDPATTERN'
PEPPER_1_ID = 'PEPPER_1_ID'
PEPPER_2_ID = 'PEPPER_2_ID'
START_MOVEMENT_ID = 'START_MOVEMENT_ID'
START_MOVEMENT_TYPE = 'START_MOVEMENT_TYPE'

# destination specification
DEST_FLOOR = 'floor'
DEST_POS = 'dest_pos'
SLACK_WEBHOOK = 'slack_webhook'
