apiVersion: v1
kind: Service
metadata:
  name: guidance
  labels:
    service: guidance
spec:
  type: ClusterIP
  selector:
    pod: guidance
  ports:
  - name: guidance
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guidance
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: guidance
    spec:
      containers:
      - name: guidance
        image: ${REPOSITORY}/tech-sketch/guidance:0.1.0
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "8888"
        - name: ORION_ENDPOINT
          value: "http://orion:1026"
        - name: DESTINATION_ENDPOINT
          value: "http://destination:8888"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ROBOT_SERVICE
          value: "${ROBOT_SERVICE}"
        - name: ROBOT_SERVICEPATH
          value: "${ROBOT_SERVICEPATH}"
        - name: ROBOT_TYPE
          value: "${ROBOT_TYPE}"
        - name: ROBOT_ID
          value: "${ROBOT_ID}"
        - name: TURTLEBOT_1_ID
          value: "${TURTLEBOT_1_ID}"
        - name: DEST_LED_SERVICE
          value: "${DEST_LED_SERVICE}"
        - name: DEST_LED_SERVICEPATH
          value: "${DEST_LED_SERVICEPATH}"
        - name: DEST_LED_TYPE
          value: "${DEST_LED_TYPE}"
        ports:
          - name: guidance
            containerPort: 8888
