apiVersion: v1
kind: Service
metadata:
  name: visualization
  labels:
    service: visualization
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  visualizer-mapping
      prefix: /visualization/
      service: http://visualization:8888
spec:
  type: ClusterIP
  selector:
    pod: visualization
  ports:
  - name: visualization
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: visualization
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: visualization
    spec:
      containers:
      - name: visualization
        image: ${REPOSITORY}/tech-sketch/visualization:0.1.0
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "8888"
        - name: PREFIX
          value: "/visualization"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: BEARER_AUTH
          value: "${BEARER_AUTH}"
        - name: MONGODB_ENDPOINT
          value: "mongodb://mongodb:27017/"
        - name: MONGODB_REPLICASET
          value: "rs0"
        - name: MONGODB_DATABASE
          value: "${MONGODB_DATABASE}"
        - name: MONGODB_COLLECTION_MAP
          value: '${MONGODB_COLLECTION_MAP}'
        - name: PIXEL_MAP
          value: '${PIXEL_MAP}'
        ports:
          - name: visualization
            containerPort: 8888
