# -*- coding: utf-8 -*-

# environment variable name
PEPPER_SERVICE = 'PEPPER_SERVICE'
PEPPER_SERVICEPATH = 'PEPPER_SERVICEPATH'
PEPPER_TYPE = 'PEPPER_TYPE'
PEPPER_2_ID = 'PEPPER_2_ID'
START_MOVEMENT_SERVICE = 'START_MOVEMENT_SERVICE'
START_MOVEMENT_SERVICEPATH = 'START_MOVEMENT_SERVICEPATH'
START_MOVEMENT_ID = 'START_MOVEMENT_ID'
START_MOVEMENT_TYPE = 'START_MOVEMENT_TYPE'
ETCD_HOST = 'ETCD_HOST'

# etcd key
ETCD_DESTINATION_KEY = '/ledger/test/destination'
