# -*- coding: utf-8 -*-

# environment variable name
PEPPER_SERVICE = 'PEPPER_SERVICE'
PEPPER_SERVICEPATH = 'PEPPER_SERVICEPATH'
PEPPER_TYPE = 'PEPPER_TYPE'
PEPPER_1_ID = 'PEPPER_1_ID'
PEPPER_2_ID = 'PEPPER_2_ID'
ROBOT_SERVICE = 'ROBOT_SERVICE'
ROBOT_SERVICEPATH = 'ROBOT_SERVICEPATH'
ROBOT_TYPE = 'ROBOT_TYPE'
START_MOVEMENT_SERVICE = 'START_MOVEMENT_SERVICE'
START_MOVEMENT_SERVICEPATH = 'START_MOVEMENT_SERVICEPATH'
START_MOVEMENT_ID = 'START_MOVEMENT_ID'
START_MOVEMENT_TYPE = 'START_MOVEMENT_TYPE'
MONGODB_URL = 'MONGODB_URL'
MONGODB_REPLICASET = 'MONGODB_REPLICASET'
FACE_API_KEY = 'FACE_API_KEY'
FACE_API_BASEURL = 'FACE_API_BASEURL'
FACE_VERIFY_DELTA_MIN = 'FACE_VERIFY_DELTA_MIN'

# current app
DEFAULT_FACE_VERIFY_DELTA_MIN = 'DEFAULT_FACE_VERIFY_DELTA_MIN'

# destination specification
DEST_FLOOR = 'floor'

# mongodb
MONGODB_DATABASE = 'ledger'
MONGODB_COLLECTION = 'visitors'

# robot state
WAITING = 'Waiting'
GUIDING = 'Guiding'
SUSPENDING = 'Suspending'
RETURNING = 'Returning'
